### ISSUE TITLE
wallet fund transfer problem

### ISSUE THREAD

**Issue by rabib-al-rise** [infinit-xyz/infinit-cli#35]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/infinit-xyz/infinit-cli/issues) for the bug I encountered.

### INFINIT CLI Version

latest

### Current Behavior

the fund  transfered fail in holesky chain into the generated wallet

### Expected Behavior

Fund transfer well in the holesky chain into the generated wallet

**Comment by melvinmcrn** [comment]
@rabib-al-rise Could you describe how you transferred the funds in Holesky? It seems there is an issue with the wallet app you used for the transfer. Could you kindly share a screenshot of the problem?

**Comment by rabib-al-rise** [comment]
copied the wallet address and transfering the fund as we it usually.
![image](https://github.com/user-attachments/assets/9044bfe8-d9b9-4932-b1db-9d687ea7718c)

**Comment by arintrongs** [comment]
Which chain did you initiated the transfer? The transfer process shouldn't be related to our stack tho.

**Comment by rabib-al-rise** [comment]
holesky testnet

**Comment by melvinmcrn** [comment]
@rabib-al-rise This issue is on your wallet or the RPC that you use. Please find a solution in Metamask's community: https://github.com/MetaMask/metamask-extension/issues.
