### ISSUE TITLE
transaction 

### ISSUE THREAD

**Issue by Lokifo** [infinit-xyz/infinit-cli#37]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/infinit-xyz/infinit-cli/issues) for the bug I encountered.

### INFINIT CLI Version

latest

### Current Behavior

✅ Simulation Completed.
ℹ Total Transactions: 11
ℹ Gas Used: 26581991 gas
ℹ Simulate Gas Price: 1 gwei
ℹ Estimated Cost: 0.026581991212655927 ETH
⠹ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 transactions).
                                                                                           ⠸ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠼ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠴ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠦ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠧ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠇ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠏ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠋ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠙ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠹ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠸ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠼ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠴ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠦ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠧ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠇ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠏ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠋ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠙ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠹ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠸ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠼ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠴ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠦ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠧ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠇ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠏ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠋ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠙ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠹ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠸ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠼ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠴ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠦ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠧ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠇ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠏ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠋ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠙ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠹ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠸ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠼ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠴ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠦ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠧ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠇ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠏ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠋ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠙ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠹ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠸ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠼ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠴ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠦ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠧ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠇ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠏ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠋ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠙ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠹ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠸ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠼ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠴ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠦ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠧ Executing DeployUniswapV3Action - DeployUniswapV3Contracts1SubAction (1/7 sub-actions, 4 ⠦ Executing DeployUniswapV3Action - SetFactoryOwnerSubAction (7/7 sub-actions, 10 transactiloki@loki:~$
loki@loki:~$ addesses.

### Expected Behavior

trasactions went through but not reflected

**Comment by melvinmcrn** [comment]
@Lokifo Please elaborate on your issue. What do you mean by "not reflected" ?

**Comment by melvinmcrn** [comment]
No further response.

**Comment by melvinmcrn** [comment]
No further response.
