### ISSUE TITLE
waited for a long time

### ISSUE THREAD

**Issue by GeorgeChen1007** [infinit-xyz/infinit-cli#38]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/infinit-xyz/infinit-cli/issues) for the bug I encountered.

### INFINIT CLI Version

@infinit-xyz/cli@0.0.0-alpha.7

### Current Behavior

![微信图片_20240415140156](https://github.com/user-attachments/assets/b328737a-65c8-4d79-855a-1fa0851b17f1)

### Expected Behavior

I don’t know if it’s a problem with my vps. I’ve been waiting here for a long time.

**Comment by melvinmcrn** [comment]
@GeorgeChen1007 Simulating the execution use https://github.com/wevm/prool which relies on foundry. Have you successfully installed foundry? (You can try running `foundry` on your terminal) If not, please install foundry from the developer doc: https://dev.infinit.tech/quick-start

**Comment by melvinmcrn** [comment]
No further response.
