### ISSUE TITLE
can not post link in channel 

### ISSUE THREAD

**Issue by wh1988105** [infinit-xyz/infinit-cli#47]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/infinit-xyz/infinit-cli/issues) for the bug I encountered.

### INFINIT CLI Version

laste

### Current Behavior

Hi there : 
i was just tried to post the link on Discord channel , however ,the system error , please check it for me ? thanks so much , my link is https://x.com/HaoWup/status/1840239661329068268 discord name "imperfect2096" 

### Expected Behavior

plase check it for me 

### Steps To Reproduce

thanks 

### Anything else?

no

**Comment by arintrongs** [comment]
Please report an issue related to the repo. Community discord has a rule to that don't allow posting a link to prevent a scam.
